upx: add patch to fix build with gcc 8
ompress_lzma.cpp:46:34: error: ‘void* memset(void*, int, size_t)’
clearing an object of non-trivial type ‘struct lzma_compress_config_t’;
use assignment or value-initialization instead [-Werror=class-memaccess]
|      memset(this, 0, sizeof(*this));
|                                   ^

For recent distro's which has gcc 8 as default like Ubuntu 18.10 and Arch Linux.

Do not apply it yet, to prevent entire rebuild.