upx: fix build with gcc 8
compress_lzma.cpp:46:34: error: ‘void* memset(void*, int, size_t)’
clearing an object of non-trivial type ‘struct lzma_compress_config_t’;
use assignment or value-initialization instead [-Werror=class-memaccess]
|      memset(this, 0, sizeof(*this));
|                                   ^

Based on:
https://github.com/01org/tbb/issues/54

I don't know if this the right patch for UPX, but it does build at least
with the minimum changes.

For recent distro's which has gcc 8 as default like Ubuntu 18.10 and Arch Linux.

TODO: Test it.